// Auto-generated by RAudioGenerator
using UnityEngine;

public static partial class R
{
    public static class Audio
    {
        public static AudioClip MouseClicked;
        public static AudioClip MouseInButton;
        public static AudioClip PanelIn;
        public static AudioClip PanelOut;
        public static AudioClip Clic05;
        public static AudioClip click;
        public static AudioClip click_2;
        public static AudioClip load;
        public static AudioClip misc_menu;
        public static AudioClip misc_menu_2;
        public static AudioClip misc_menu_4;
        public static AudioClip misc_sound;
        public static AudioClip negative;
        public static AudioClip negative_2;
        public static AudioClip part;
        public static AudioClip positive;
        public static AudioClip save;
        public static AudioClip sharp_echo;
        public static AudioClip Upper01;
        public static AudioClip Wrong_Error;
    }

    public static void InitAudio()
    {
        Audio.MouseClicked = Resources.Load<AudioClip>("Audio/MouseClicked");
        Audio.MouseInButton = Resources.Load<AudioClip>("Audio/MouseInButton");
        Audio.PanelIn = Resources.Load<AudioClip>("Audio/PanelIn");
        Audio.PanelOut = Resources.Load<AudioClip>("Audio/PanelOut");
        Audio.Clic05 = Resources.Load<AudioClip>("Audio/Bank/Clic05");
        Audio.click = Resources.Load<AudioClip>("Audio/Bank/click");
        Audio.click_2 = Resources.Load<AudioClip>("Audio/Bank/click_2");
        Audio.load = Resources.Load<AudioClip>("Audio/Bank/load");
        Audio.misc_menu = Resources.Load<AudioClip>("Audio/Bank/misc_menu");
        Audio.misc_menu_2 = Resources.Load<AudioClip>("Audio/Bank/misc_menu_2");
        Audio.misc_menu_4 = Resources.Load<AudioClip>("Audio/Bank/misc_menu_4");
        Audio.misc_sound = Resources.Load<AudioClip>("Audio/Bank/misc_sound");
        Audio.negative = Resources.Load<AudioClip>("Audio/Bank/negative");
        Audio.negative_2 = Resources.Load<AudioClip>("Audio/Bank/negative_2");
        Audio.part = Resources.Load<AudioClip>("Audio/Bank/part");
        Audio.positive = Resources.Load<AudioClip>("Audio/Bank/positive");
        Audio.save = Resources.Load<AudioClip>("Audio/Bank/save");
        Audio.sharp_echo = Resources.Load<AudioClip>("Audio/Bank/sharp_echo");
        Audio.Upper01 = Resources.Load<AudioClip>("Audio/Bank/Upper01");
        Audio.Wrong_Error = Resources.Load<AudioClip>("Audio/Bank/Wrong Error");
    }
}
